services:
    setono_sylius_mailchimp.context.locale:
        class: Setono\SyliusMailchimpPlugin\Context\LocaleContext
        arguments:
            - "@sylius.repository.locale"
            - "@sylius.context.locale"

    setono_sylius_mailchimp.context.config:
        class: Setono\SyliusMailchimpPlugin\Context\MailchimpConfigContext
        public: true
        arguments:
            - "@setono_sylius_mailchimp.repository.config"
            - "@setono_sylius_mailchimp.repository.list"
            - "@sylius.context.channel"
            - "@setono_sylius_mailchimp.context.locale"
            - "@setono_sylius_mailchimp.factory.config"
            - "@setono_sylius_mailchimp.factory.list"
            - "@setono_sylius_mailchimp.manager.config"
