services:
    setono_sylius_mailchimp.controller.action.export_to_mailchimp:
        class: Setono\SyliusMailchimpPlugin\Controller\Action\ExportToMailchimpAction
        public: true
        arguments:
            - "@setono_sylius_mailchimp.exporter.customer_newsletter"
            - "@setono_sylius_mailchimp.context.config"
            - "@session.flash_bag"
            - "@translator"
            - "@router"

    setono_sylius_mailchimp.controller.action.subscribe_to_newsletter:
        class: Setono\SyliusMailchimpPlugin\Controller\Action\SubscribeToNewsletterAction
        public: true
        arguments:
            - "@setono_sylius_mailchimp.validator.newsletter_email"
            - "@security.csrf.token_manager"
            - "@setono_sylius_mailchimp.handler.newsletter_subscription"
            - "@translator"
            - "@setono_sylius_mailchimp.handler.newsletter_subscription"
