services:
    setono_sylius_mailchimp_export_plugin.context.locale:
        class: Setono\SyliusMailchimpPlugin\Context\LocaleContext
        arguments:
            - "@sylius.repository.locale"
            - "@sylius.context.locale"

    setono_sylius_mailchimp_export_plugin.context.config:
        class: Setono\SyliusMailchimpPlugin\Context\MailchimpConfigContext
        public: true
        arguments:
            - "@setono_sylius_mailchimp_export_plugin.repository.config"
            - "@setono_sylius_mailchimp_export_plugin.repository.list"
            - "@sylius.context.channel"
            - "@setono_sylius_mailchimp_export_plugin.context.locale"
            - "@setono_sylius_mailchimp_export_plugin.factory.config"
            - "@setono_sylius_mailchimp_export_plugin.factory.list"
            - "@setono_sylius_mailchimp_export_plugin.manager.config"
