services:
    setono_sylius_mailchimp.form.type.config:
        class: Setono\SyliusMailchimpPlugin\Form\Type\MailchimpConfigType
        arguments:
            - "%setono_sylius_mailchimp.model.config.class%"
            - ['setono']
        tags:
            - { name: form.type }

    setono_sylius_mailchimp.form.type.list:
        class: Setono\SyliusMailchimpPlugin\Form\Type\MailchimpListType
        arguments:
            - "%setono_sylius_mailchimp.model.list.class%"
            - ['setono']
        tags:
            - { name: form.type }
