services:
    setono_sylius_mailchimp_export_plugin.listener.menu.mailchimp_config:
        class: Setono\SyliusMailChimpPlugin\Menu\MailChimpConfigMenuBuilder
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addConfigItem }
        arguments:
            - "@setono_sylius_mailchimp_export_plugin.context.config"

    setono_sylius_mailchimp_export_plugin.listener.menu.mailchimp_export:
        class: Setono\SyliusMailChimpPlugin\Menu\MailChimpExportMenuBuilder
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addMarketingItem }
