imports:
    - { resource: grids/mailchimp_export.yml }

sylius_grid:
    templates:
        action:
            mailchimp_export: "@SetonoSyliusMailChimpPlugin/MailChimpExport/Grid/Action/export.html.twig"
