imports:
    - { resource: services/form.yml }
    - { resource: services/menu.yml }
    - { resource: services/context.yml }

services:
    setono_sylius_mailchimp.api_client.mailchimp:
        class: Setono\SyliusMailchimpPlugin\ApiClient\MailchimpApiClient
        public: true
        arguments:
            - "@setono_sylius_mailchimp.context.config"

    setono_sylius_mailchimp.event_listener.customer_listener:
        class: Setono\SyliusMailchimpPlugin\EventListener\CustomerNewsletterListener
        arguments:
            - "@sylius.repository.customer"
            - "@setono_sylius_mailchimp.api_client.mailchimp"
            - "@setono_sylius_mailchimp.context.config"
            - "@sylius.context.channel"
            - "@setono_sylius_mailchimp.context.locale"
            - "@setono_sylius_mailchimp.manager.list"
            - "@logger"
            - ['sylius_shop_register', 'sylius_shop_account_profile_update']
        tags:
            - { name: "kernel.event_listener", event: "kernel.terminate", method: manageSubscription }

    setono_sylius_mailchimp.event_listener.order_listener:
        class: Setono\SyliusMailchimpPlugin\EventListener\OrderListener
        arguments:
            - "@sylius.repository.order"
            - "@setono_sylius_mailchimp.api_client.mailchimp"
            - "@logger"
            - ['sylius_shop_order_thank_you']
        tags:
            - { name: "kernel.event_listener", event: "kernel.terminate", method: manageOrderSubscription }

    setono_sylius_mailchimp.repository.customer:
        class: Setono\SyliusMailchimpPlugin\Repository\CustomerRepository
        arguments:
            - "@sylius.repository.customer"
            - "@setono_sylius_mailchimp.repository.export"

    setono_sylius_mailchimp.exporter.customer_newsletter:
        class: Setono\SyliusMailchimpPlugin\Exporter\CustomerNewsletterExporter
        public: true
        arguments:
            - "@setono_sylius_mailchimp.factory.export"
            - "@setono_sylius_mailchimp.repository.export"
            - "@setono_sylius_mailchimp.repository.customer"
            - "@sylius.context.channel"
            - "@setono_sylius_mailchimp.context.locale"
            - "@sylius.repository.locale"
            - "@setono_sylius_mailchimp.context.config"
            - "@setono_sylius_mailchimp.api_client.mailchimp"
            - "@setono_sylius_mailchimp.manager.export"
            - "@setono_sylius_mailchimp.manager.list"

    setono_sylius_mailchimp.exporter.customer_order:
        class: Setono\SyliusMailchimpPlugin\Exporter\CustomerOrderExporter
        public: true
        arguments:
            - "@setono_sylius_mailchimp.api_client.mailchimp"

    setono_sylius_mailchimp.controller.action.export_to_mailchimp:
        class: Setono\SyliusMailchimpPlugin\Controller\Action\ExportToMailchimpAction
        public: true
        arguments:
            - "@setono_sylius_mailchimp.exporter.customer_newsletter"
            - "@setono_sylius_mailchimp.context.config"
            - "@session.flash_bag"
            - "@translator"
            - "@router"

    setono_sylius_mailchimp.command.export_to_mailchimp:
        class: Setono\SyliusMailchimpPlugin\Command\ExportToMailchimpCommand
        arguments:
            - "@setono_sylius_mailchimp.exporter.customer_newsletter"
        tags:
            - { name: console.command }

    setono_sylius_mailchimp.form.extension.type.checkout.complete:
        class: Setono\SyliusMailchimpPlugin\Form\Extension\CompleteTypeExtension
        tags:
            - { name: form.type_extension }
