imports:
    - { resource: services/form.yml }
    - { resource: services/menu.yml }
    - { resource: services/context.yml }

services:
    setono_sylius_mailchimp_export_plugin.api_client.mailchimp:
        class: Setono\SyliusMailchimpPlugin\ApiClient\MailchimpApiClient
        public: true
        arguments:
            - "@setono_sylius_mailchimp_export_plugin.context.config"

    setono_sylius_mailchimp_export_plugin.event_listener.customer_listener:
        class: Setono\SyliusMailchimpPlugin\EventListener\CustomerNewsletterListener
        arguments:
            - "@setono_sylius_mailchimp_export_plugin.api_client.mailchimp"
            - "@setono_sylius_mailchimp_export_plugin.context.config"
            - "@sylius.context.channel"
            - "@setono_sylius_mailchimp_export_plugin.context.locale"
            - "@setono_sylius_mailchimp_export_plugin.manager.list"
        tags:
            - { name: "kernel.event_listener", event: "sylius.customer.post_register", method: manageSubscription }
            - { name: "kernel.event_listener", event: "sylius.customer.pre_update", method: manageSubscription }

    setono_sylius_mailchimp_export_plugin.repository.customer:
        class: Setono\SyliusMailchimpPlugin\Repository\CustomerRepository
        arguments:
            - "@sylius.repository.customer"
            - "@setono_sylius_mailchimp_export_plugin.repository.export"

    setono_sylius_mailchimp_export_plugin.exporter.customer_newsletter:
        class: Setono\SyliusMailchimpPlugin\Exporter\CustomerNewsletterExporter
        public: true
        arguments:
            - "@setono_sylius_mailchimp_export_plugin.factory.export"
            - "@setono_sylius_mailchimp_export_plugin.repository.export"
            - "@setono_sylius_mailchimp_export_plugin.repository.customer"
            - "@sylius.context.channel"
            - "@setono_sylius_mailchimp_export_plugin.context.locale"
            - "@setono_sylius_mailchimp_export_plugin.context.config"
            - "@setono_sylius_mailchimp_export_plugin.api_client.mailchimp"
            - "@setono_sylius_mailchimp_export_plugin.manager.export"
            - "@setono_sylius_mailchimp_export_plugin.manager.list"

    setono_sylius_mailchimp_export_plugin.controller.action.export_to_mailchimp:
        class: Setono\SyliusMailchimpPlugin\Controller\Action\ExportToMailchimpAction
        public: true
        arguments:
            - "@setono_sylius_mailchimp_export_plugin.exporter.customer_newsletter"
            - "@setono_sylius_mailchimp_export_plugin.context.config"
            - "@session.flash_bag"
            - "@translator"
            - "@router"

    setono_sylius_mailchimp_export_plugin.controller.cli.command.export_to_mailchimp:
        class: Setono\SyliusMailchimpPlugin\Cli\Command\ExportToMailchimpCommand
        arguments:
            - "@setono_sylius_mailchimp_export_plugin.exporter.customer_newsletter"
        tags:
            - { name: console.command }
