winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                setono_mailchimp_export_customer:
                    on: ["complete"]
                    do: ["@setono_sylius_mailchimp.exporter.customer_newsletter", "exportSingleCustomerForOrder"]
                    args: ["object"]
