sylius_resource:
    resources:
        setono_sylius_mailchimp.export:
            driver: doctrine/orm
            classes:
                model: Setono\SyliusMailchimpPlugin\Entity\MailchimpExport
                interface: Setono\SyliusMailchimpPlugin\Entity\MailchimpExportInterface
                repository: Setono\SyliusMailchimpPlugin\Repository\MailchimpExportRepository
